### ISSUE TITLE
Site is down

### ISSUE THREAD

**Issue by archiewood** [astrowonk/emoji_finder#6]
I love this app and use it pretty much daily.

Let me know if I can help, or prepared to self host otherwise!

<img width="625" alt="CleanShot 2023-09-05 at 10 03 10@2x" src="https://github.com/astrowonk/emoji_finder/assets/58074498/661aed21-4d6f-45b8-9799-78020f59253c">

**Comment by astrowonk** [comment]
Hey thanks, sorry I messed up some permissions on the server. Should be back and running now.

I do have a local version for Macs, [a Launchbar Action](https://github.com/astrowonk/Emoji-Semantic-Search-LaunchBar-Action) if that's of any interest!
